#!/usr/bin/env bash

# CS TEMPLATES - FREENODE EDITION
# https://freenode.net/channel_guidelines.shtml

# This script generates commands which can be copy-pasted to Atheme's
# ChanServ to set templates which can later be set with flags.

# With these templates only bots are opped, because most of bots expect
# to be opped. See also the link on line 4.

## ChanServ settings
# Tell ChanServ to be on channel. Not needed for larger channels
echo "/cs set $1 GUARD ON"

# Disables ChanServ MLOCK
echo "/cs set $1 MLOCK"

# Allow channel information to be seen
echo "/cs set $1 PRIVATE OFF"

# Sync flags when they are changed
echo "/cs set $1 NOSYNC OFF"

# Allow only identified users to be opped
echo "/cs set $1 SECURE ON"

# Allow only users with +t flag to change topic
echo "/cs set $1 TOPICLOCK ON"

# Allows everyone to see ACL changes.
echo "/cs set $1 VERBOSE ON"

## ChanServ templates
# Channel founder who can do anything they want.
echo "/cs template $1 founder !-aqOVH+*F"

# Successor will get all flags in the end and if they cannot be trusted
# with them now, they really shouldn't be successor.
echo "/cs template $1 successor !-aqOVH+*S"

# Super op, be able to do everything with services
echo "/cs template $1 sop !-aqOVH+*"

# Normal op, be able to invite, invite, kick, kickban, unban, change topic
# give this also to $OPER or network operator host
# start by disabling oper as it causes conflict otherwise
echo "/cs template $1 oper -*"
echo "/cs template $1 op !-*+voirtAo"

# Half op, be able to do everything else than kick other halfops & higher
echo "/cs template $1 hop !-*+virtAh"

# Bot which doesn't need to be able to do so much.
echo "/cs template $1 bot !-*+Ooirt"

# Half op bot which doesn't need to be able to do even that much
echo "/cs template $1 hbot !-*+Hhirt"

# Permanent ban. Removes all flags and sets autokick.
echo "/cs template $1 ban !-*+b"
