#!/usr/bin/env bash
cd /usr/local/bin
curl -LO https://github.com/Mkaysi/gist/raw/master/cryptocurrency/start/multibit
chmod +x multibit
curl -LO https://github.com/Mkaysi/gist/raw/master/cryptocurrency/start/multidoge
chmod 755 multidoge
cd
